/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractAbi {
    #[serde(rename = "abi")]
    pub abi: Vec<::std::collections::HashMap<String, String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "relevance")]
    pub relevance: i32,
}

impl ContractAbi {
    pub fn new(abi: Vec<::std::collections::HashMap<String, String>>, description: String, relevance: i32) -> ContractAbi {
        ContractAbi {
            abi,
            description,
            relevance,
        }
    }
}


