/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DelegateDelete {
    #[serde(rename = "delegate")]
    pub delegate: String,
    #[serde(rename = "delegator")]
    pub delegator: String,
    #[serde(rename = "signature")]
    pub signature: String,
}

impl DelegateDelete {
    pub fn new(delegate: String, delegator: String, signature: String) -> DelegateDelete {
        DelegateDelete {
            delegate,
            delegator,
            signature,
        }
    }
}


