/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Erc20Info {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimals")]
    pub decimals: i32,
    #[serde(rename = "logoUri")]
    pub logo_uri: String,
}

impl Erc20Info {
    pub fn new(name: String, symbol: String, decimals: i32, logo_uri: String) -> Erc20Info {
        Erc20Info {
            name,
            symbol,
            decimals,
            logo_uri,
        }
    }
}


