/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IndexingStatus {
    #[serde(rename = "currentBlockNumber")]
    pub current_block_number: i32,
    #[serde(rename = "erc20BlockNumber")]
    pub erc20_block_number: i32,
    #[serde(rename = "erc20Synced")]
    pub erc20_synced: bool,
    #[serde(rename = "masterCopiesBlockNumber")]
    pub master_copies_block_number: i32,
    #[serde(rename = "masterCopiesSynced")]
    pub master_copies_synced: bool,
    #[serde(rename = "synced")]
    pub synced: bool,
}

impl IndexingStatus {
    pub fn new(current_block_number: i32, erc20_block_number: i32, erc20_synced: bool, master_copies_block_number: i32, master_copies_synced: bool, synced: bool) -> IndexingStatus {
        IndexingStatus {
            current_block_number,
            erc20_block_number,
            erc20_synced,
            master_copies_block_number,
            master_copies_synced,
            synced,
        }
    }
}


