/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MasterCopyResponse {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "deployer")]
    pub deployer: String,
    #[serde(rename = "deployedBlockNumber")]
    pub deployed_block_number: i32,
    #[serde(rename = "lastIndexedBlockNumber")]
    pub last_indexed_block_number: i32,
    #[serde(rename = "l2")]
    pub l2: bool,
}

impl MasterCopyResponse {
    pub fn new(address: String, version: String, deployer: String, deployed_block_number: i32, last_indexed_block_number: i32, l2: bool) -> MasterCopyResponse {
        MasterCopyResponse {
            address,
            version,
            deployer,
            deployed_block_number,
            last_indexed_block_number,
            l2,
        }
    }
}


