/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModulesResponse {
    #[serde(rename = "safes")]
    pub safes: Vec<String>,
}

impl ModulesResponse {
    pub fn new(safes: Vec<String>) -> ModulesResponse {
        ModulesResponse {
            safes,
        }
    }
}


