/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeMultisigTransactionEstimateResponse {
    #[serde(rename = "safeTxGas")]
    pub safe_tx_gas: String,
}

impl SafeMultisigTransactionEstimateResponse {
    pub fn new(safe_tx_gas: String) -> SafeMultisigTransactionEstimateResponse {
        SafeMultisigTransactionEstimateResponse {
            safe_tx_gas,
        }
    }
}


