/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeMessageSignature {
    #[serde(rename = "signature")]
    pub signature: String,
}

impl SafeMessageSignature {
    pub fn new(signature: String) -> SafeMessageSignature {
        SafeMessageSignature {
            signature,
        }
    }
}


