/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeDelegateResponse {
    #[serde(rename = "safe")]
    pub safe: String,
    #[serde(rename = "delegate")]
    pub delegate: String,
    #[serde(rename = "delegator")]
    pub delegator: String,
    #[serde(rename = "label")]
    pub label: String,
}

impl SafeDelegateResponse {
    pub fn new(safe: String, delegate: String, delegator: String, label: String) -> SafeDelegateResponse {
        SafeDelegateResponse {
            safe,
            delegate,
            delegator,
            label,
        }
    }
}


