/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeCreationInfoResponse {
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "creator")]
    pub creator: String,
    #[serde(rename = "transactionHash")]
    pub transaction_hash: String,
    #[serde(rename = "factoryAddress")]
    pub factory_address: String,
    #[serde(rename = "masterCopy", deserialize_with = "Option::deserialize")]
    pub master_copy: Option<String>,
    #[serde(rename = "setupData", deserialize_with = "Option::deserialize")]
    pub setup_data: Option<String>,
    #[serde(rename = "dataDecoded", skip_serializing_if = "Option::is_none")]
    pub data_decoded: Option<String>,
}

impl SafeCreationInfoResponse {
    pub fn new(created: String, creator: String, transaction_hash: String, factory_address: String, master_copy: Option<String>, setup_data: Option<String>) -> SafeCreationInfoResponse {
        SafeCreationInfoResponse {
            created,
            creator,
            transaction_hash,
            factory_address,
            master_copy,
            setup_data,
            data_decoded: None,
        }
    }
}


