/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeModuleTransactionWithTransfersResponse {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "executionDate")]
    pub execution_date: String,
    #[serde(rename = "blockNumber", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<i32>,
    #[serde(rename = "isSuccessful", skip_serializing_if = "Option::is_none")]
    pub is_successful: Option<bool>,
    #[serde(rename = "transactionHash", skip_serializing_if = "Option::is_none")]
    pub transaction_hash: Option<String>,
    #[serde(rename = "safe")]
    pub safe: String,
    #[serde(rename = "module")]
    pub module: String,
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<String>,
    #[serde(rename = "operation")]
    pub operation: i32,
    #[serde(rename = "dataDecoded", skip_serializing_if = "Option::is_none")]
    pub data_decoded: Option<String>,
    #[serde(rename = "moduleTransactionId", skip_serializing_if = "Option::is_none")]
    pub module_transaction_id: Option<String>,
    #[serde(rename = "transfers")]
    pub transfers: Vec<crate::models::TransferWithTokenInfoResponse>,
    #[serde(rename = "txType", skip_serializing_if = "Option::is_none")]
    pub tx_type: Option<String>,
}

impl SafeModuleTransactionWithTransfersResponse {
    pub fn new(execution_date: String, safe: String, module: String, to: String, value: String, data: Option<String>, operation: i32, transfers: Vec<crate::models::TransferWithTokenInfoResponse>) -> SafeModuleTransactionWithTransfersResponse {
        SafeModuleTransactionWithTransfersResponse {
            created: None,
            execution_date,
            block_number: None,
            is_successful: None,
            transaction_hash: None,
            safe,
            module,
            to,
            value,
            data,
            operation,
            data_decoded: None,
            module_transaction_id: None,
            transfers,
            tx_type: None,
        }
    }
}


