/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeMultisigTransaction {
    #[serde(rename = "safe")]
    pub safe: String,
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    #[serde(rename = "operation")]
    pub operation: i32,
    #[serde(rename = "gasToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gas_token: Option<Option<String>>,
    #[serde(rename = "safeTxGas")]
    pub safe_tx_gas: i32,
    #[serde(rename = "baseGas")]
    pub base_gas: i32,
    #[serde(rename = "gasPrice")]
    pub gas_price: i32,
    #[serde(rename = "refundReceiver", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refund_receiver: Option<Option<String>>,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "contractTransactionHash")]
    pub contract_transaction_hash: String,
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "signature", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Option<String>>,
    #[serde(rename = "origin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Option<String>>,
}

impl SafeMultisigTransaction {
    pub fn new(safe: String, to: String, value: i32, operation: i32, safe_tx_gas: i32, base_gas: i32, gas_price: i32, nonce: i32, contract_transaction_hash: String, sender: String) -> SafeMultisigTransaction {
        SafeMultisigTransaction {
            safe,
            to,
            value,
            data: None,
            operation,
            gas_token: None,
            safe_tx_gas,
            base_gas,
            gas_price,
            refund_receiver: None,
            nonce,
            contract_transaction_hash,
            sender,
            signature: None,
            origin: None,
        }
    }
}


