/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeMultisigTransactionEstimate {
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    #[serde(rename = "operation")]
    pub operation: i32,
}

impl SafeMultisigTransactionEstimate {
    pub fn new(to: String, value: i32, operation: i32) -> SafeMultisigTransactionEstimate {
        SafeMultisigTransactionEstimate {
            to,
            value,
            data: None,
            operation,
        }
    }
}


