/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeBalanceResponse {
    #[serde(rename = "tokenAddress")]
    pub token_address: String,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Erc20Info>,
    #[serde(rename = "balance")]
    pub balance: String,
}

impl SafeBalanceResponse {
    pub fn new(token_address: String, token: crate::models::Erc20Info, balance: String) -> SafeBalanceResponse {
        SafeBalanceResponse {
            token_address,
            token: Box::new(token),
            balance,
        }
    }
}


