/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeInfoResponse {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "threshold")]
    pub threshold: i32,
    #[serde(rename = "owners")]
    pub owners: Vec<String>,
    #[serde(rename = "masterCopy")]
    pub master_copy: String,
    #[serde(rename = "modules")]
    pub modules: Vec<String>,
    #[serde(rename = "fallbackHandler")]
    pub fallback_handler: String,
    #[serde(rename = "guard")]
    pub guard: String,
    #[serde(rename = "version", deserialize_with = "Option::deserialize")]
    pub version: Option<String>,
}

impl SafeInfoResponse {
    pub fn new(address: String, nonce: i32, threshold: i32, owners: Vec<String>, master_copy: String, modules: Vec<String>, fallback_handler: String, guard: String, version: Option<String>) -> SafeInfoResponse {
        SafeInfoResponse {
            address,
            nonce,
            threshold,
            owners,
            master_copy,
            modules,
            fallback_handler,
            guard,
            version,
        }
    }
}


