/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SafeMessage {
    #[serde(rename = "message")]
    pub message: serde_json::Value,
    #[serde(rename = "safeAppId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub safe_app_id: Option<Option<i32>>,
    #[serde(rename = "signature")]
    pub signature: String,
}

impl SafeMessage {
    pub fn new(message: serde_json::Value, signature: String) -> SafeMessage {
        SafeMessage {
            message,
            safe_app_id: None,
            signature,
        }
    }
}


