/*
 * Safe Transaction Service API
 *
 * API to keep track of transactions sent via Gnosis Safe smart contracts
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokenPriceResponse {
    #[serde(rename = "fiatCode")]
    pub fiat_code: String,
    #[serde(rename = "fiatPrice")]
    pub fiat_price: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl TokenPriceResponse {
    pub fn new(fiat_code: String, fiat_price: String, timestamp: String) -> TokenPriceResponse {
        TokenPriceResponse {
            fiat_code,
            fiat_price,
            timestamp,
        }
    }
}


